### ISSUE TITLE
Import Book List

### ISSUE THREAD

**Issue by agdacjm** [tw-library/library-app#1]
# Description
- This task consists on importing the "Biblioteca de BH" spreadsheet into the TW Library database.
- The spreadsheet is available at:
  https://docs.google.com/a/thoughtworks.com/spreadsheets/d/18tvdummwo5B3igSddiz3xPCAAt1ey6YenBp6JSeYe8M/edit?usp=sharing
- The spreadsheet should feed the Book List.
- The following fields should be imported from the spreadsheet to the  TW Library database: 
  - Title
  - Author
  - User with the borrowed book. The use is the first part of the e-mail string. Ex: "fpio@thoughtworks.com" contains the username "fpio".
  - Donator's name
  - Users on the Waiting List. The user is the first part of the e-mail string. Ex: "fpio@thoughtworks.com" contains the username "fpio".
- Also, for every book entry imported into the database, a unique numeric identifier should be generated.

**Comment by agdacjm** [comment]
# Description

This task consists on importing the "Biblioteca de BH" spreadsheet into the TW Library database.

The spreadsheet is available at:

https://docs.google.com/a/thoughtworks.com/spreadsheets/d/18tvdummwo5B3igSddiz3xPCAAt1ey6YenBp6JSeYe8M/edit?usp=sharing

The following fields should be imported from the spreadsheet to the database: 

- Title
- Author
- Username. The username is the first part of the e-mail string. Ex: "fpio@thoughtworks.com" contains the username "fpio".

Also, for every book entry imported into the database, a unique numeric identifier should be generated.

**Comment by tiagovinicius** [comment]
This story is replaced by 2 stories:
- Add a book to library #33 
- Autocomplete the book information #34
