### ISSUE TITLE
Access a Library

### ISSUE THREAD

**Issue by tiagovinicius** [tw-library/library-app#41]
**As a library user 
I want to interact with Library of my office
So I can get the book that I need**
## Out of Scope

Add a Library #45
## Acceptance criteria

Given each library has a different link to access
When the users access the library system with his library link
Then the users should interact with the books from his library only
And the users should not interact with the books from other libraries

Given each library has a different link to access
When the users access a link to a library that doesn't exists 
Then they receive a message 'Oops! The library you are looking for does not exist yet. Want to try out one of the following?'
And see the available links to libraries

Given each library has a different link to access
When the users access a link that doesn't have a library id
Then they receive a  message 'Oops! The library you are looking for does not exist yet. Want to try out one of the following?'
And see the available links to libraries

Given each library has a different link to access
When the users access the system root link
Then they receive a  message 'Oops! The library you are looking for does not exist yet. Want to try out one of the following?'
And see the available links to libraries

**Comment by ekowcharles** [comment]
Hides the 'Add Book' button if user is not already in a library.

**Comment by lucastfa** [comment]
To fix:
1. (FIXED) The 'ALL BOOKS' link in the tab should redirect the user to the library he is navigating.
2. (FIXED) When the user access the system with 'env.herokuapp.com/#/' only the system should display the same page displayed when the user access with a link for an inexistent library (related to the third acceptance criteria).
