### ISSUE TITLE
View book details

### ISSUE THREAD

**Issue by agdacjm** [tw-library/library-app#8]
**As a library user 
I want to view book details (unique ID, title, subtitle, authors, description/about/presentation, ISBN 10 and 13, publisher, publication date, number of pages, donator, image, status)
So that I can evaluate more accurately my interest in borrowing a book**
## Out of Scope

Insert a book review #9
## Notes
- The Book Details Page should be a new page opened from the Book List Page.
- "View book details" option should be displayed for all registered books.
## Acceptance criteria

Given the book is listed on the Book List Page
When the user attempts to view the book details
And the book has these information available
Then s/he views a page with book details 

Given the book is listed on the Book List Page
When the user attempts to view the book details
And the book has not these information available
Then s/he doesn't view a page with book details 
## Prototype

To be attached

**Comment by tiagovinicius** [comment]
UX done!
